version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  airflow-webserver:
    build: .
    image: apache/airflow:2.7.1-python3.9
    restart: always
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      # ✅ Reddit API credentials
      REDDIT_CLIENT_ID: "PZv8o9495wb8fPhXhxlerw"
      REDDIT_CLIENT_SECRET: "_y8Od8TqxUM0m1FAKNILDsC3GiR28A"
      REDDIT_USER_AGENT: "Datapipelinebuild"
      REDDIT_USERNAME: "vizayyyyyy"
      REDDIT_PASSWORD: "VIjaymuni55@"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - redis

  airflow-scheduler:
    build: .
    image: apache/airflow:2.7.1-python3.9
    restart: always
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      # ✅ Reddit API credentials
      REDDIT_CLIENT_ID: "PZv8o9495wb8fPhXhxlerw"
      REDDIT_CLIENT_SECRET: "_y8Od8TqxUM0m1FAKNILDsC3GiR28A"
      REDDIT_USER_AGENT: "Datapipelinebuild"
      REDDIT_USERNAME: "vizayyyyyy"
      REDDIT_PASSWORD: "VIjaymuni55@"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - redis

  airflow-worker:
    build: .
    image: apache/airflow:2.7.1-python3.9
    restart: always
    command: celery worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      # ✅ Reddit API credentials
      REDDIT_CLIENT_ID: "PZv8o9495wb8fPhXhxlerw"
      REDDIT_CLIENT_SECRET: "_y8Od8TqxUM0m1FAKNILDsC3GiR28A"
      REDDIT_USER_AGENT: "Datapipelinebuild"
      REDDIT_USERNAME: "vizayyyyyy"
      REDDIT_PASSWORD: "VIjaymuni55@"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - redis

  airflow-init:
    build: .
    image: apache/airflow:2.7.1-python3.9
    restart: "no"
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      # ✅ Reddit API credentials
      REDDIT_CLIENT_ID: "PZv8o9495wb8fPhXhxlerw"
      REDDIT_CLIENT_SECRET: "_y8Od8TqxUM0m1FAKNILDsC3GiR28A"
      REDDIT_USER_AGENT: "Datapipelinebuild"
      REDDIT_USERNAME: "vizayyyyyy"
      REDDIT_PASSWORD: "VIjaymuni55@"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - redis

volumes:
  postgres-db-volume:
